#!/bin/bash
export VITE_SUPABASE_URL=https://soztmmpxexhblcpeflfk.supabase.co
export VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvenRtbXB4ZXhoYmxjcGVmbGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0MjYwNDYsImV4cCI6MjA4ODAwMjA0Nn0.4hmR2I1MtTs0JfroZru1D8UVH6EVt9MeKR9ddEAA5Z4
export GROQ_API_KEY=your_groq_api_key
export ONEMAP_EMAIL=your_onemap_email
export ONEMAP_PASSWORD=your_onemap_password
node server.js
